insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Vector Energy Bar', 88.94);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Flour - Fast / Rapid', 97.5);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Bagel - Ched Chs Presliced', 38.12);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Juice - Grape, White', 66.91);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cookies - Englishbay Wht', 32.29);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Chicken - Bones', 4.76);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Vinegar - White', 4.33);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Flavouring - Rum', 81.09);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Oil - Coconut', 48.85);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Beer - Mill St Organic', 34.04);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Steampan Lid', 8.73);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Fish - Scallops, Cold Smoked', 11.17);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Sauce - Bernaise, Mix', 6.08);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Magnotta, Merlot Sr Vqa', 32.66);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Chenin Blanc K.w.v.', 32.69);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Vector Energy Bar', 39.99);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Gelatine Leaves - Bulk', 64.63);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Squid - Tubes / Tenticles 10/20', 73.81);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Grouper - Fresh', 43.0);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Juice - Orange, 341 Ml', 57.26);
